import Head from 'next/head'
import SignInComponent from 'components/auth/SignIn'

const SignIn = () => {
  return (
    <>
      <Head>
        <title>Sign In - QuranTracker</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SignInComponent />{' '}
    </>
  )
}

export default SignIn
