import Head from 'next/head'
import SignUpComponent from 'components/auth/SignUp'

const SignUp = () => {
  return (
    <>
      <Head>
        <title>Sign Up - QuranTracker</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SignUpComponent />
    </>
  )
}

export default SignUp
